import Head from "next/head";
import Image from "next/image";
import Features from "../src/components/Features";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold font-primary underline text-gray-900 md:text-red-500 text-underline lg:no-underline">
        Hello world!
      </h1>
      <button className="btn-primary">Say Hello</button>
      <Features></Features>
    </div>
  );
}
