import Head from "next/head";
import Image from "next/image";
import Banner from "../src/components/Banner";
import Footer from "../src/Components/Footer";
import Header from "../src/Components/Header";
import Testimonial from "../src/components/Testimonial";
import CTA from "../src/components/CTA";
import Features from "../src/components/Features";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Banner />
        <Features />
        <Testimonial />
        <CTA />
        <Footer />
      </main>
    </div>
  );
}
