import Head from "next/head";
import Image from "next/image";
import Banner from "../src/Components/Banner";
import CallToAction from "../src/Components/CallToAction";
import Footer from "../src/Components/Footer";
import Header from "../src/Components/Header";
import Services from "../src/Components/Services";
import Testimonial from "../src/Components/Testimonial";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Banner />
        <Services />
        <Testimonial />
        <CallToAction />
        <Footer />
      </main>
    </div>
  );
}
